#!/bin/bash

#
# For documentation and license see https://github.com/darule0/sparkdiff/
#
GIT_INSTALLED="1"
command -v git >/dev/null 2>&1 ||
{ 
 GIT_INSTALLED="0"
}
if [ ! -d "~/bin" ] 
then
 mkdir -p ~/bin
 chmod u+rx ~/bin
fi
rm -fr ${HOME}/.sparkdiff.dd4b66ed-a43d-48ec-8e32-1b901bc8ea8e
mkdir ${HOME}/.sparkdiff.dd4b66ed-a43d-48ec-8e32-1b901bc8ea8e
chmod u+rx ${HOME}/.sparkdiff.dd4b66ed-a43d-48ec-8e32-1b901bc8ea8e
if [ "$GIT_INSTALLED" -eq "1" ]; then
 git clone https://github.com/darule0/sparkdiff.git ${HOME}/.sparkdiff.dd4b66ed-a43d-48ec-8e32-1b901bc8ea8e/ >> /dev/null 2>> /dev/null
else
 wget -O ${HOME}/.sparkdiff.dd4b66ed-a43d-48ec-8e32-1b901bc8ea8e/sparkdiff.sh https://github.com/darule0/sparkdiff/blob/main/sparkdiff.sh?raw=true >> /dev/null 2>> /dev/null
fi
chmod u+rx ${HOME}/.sparkdiff.dd4b66ed-a43d-48ec-8e32-1b901bc8ea8e/sparkdiff.sh
${HOME}/.sparkdiff.dd4b66ed-a43d-48ec-8e32-1b901bc8ea8e/sparkdiff.sh $@
